#!/usr/bin/env bash
# Installs Nginx and configures its root page to display Holberton School

apt-get update
apt-get -y install nginx
printf '%s\n' "Holberton School for the win!" > /var/www/html/index.html
service nginx restart
