#!/usr/bin/env bash
# Installs Nginx and configures a permanent redirect for /redirect_me.

apt-get update
apt-get install -y nginx

sed -i '/server_name _;/a\        location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

nginx -t
service nginx restart
